# This is a basic workflow to help you get started with Actions

name: GitHub Followed Ranking

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    # Runs at 4am JST
    - cron: '20 19 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl -s https://raw.githubusercontent.com/gayanvoice/top-github-users/main/cache/japan.json | jq 'to_entries | .[] | select(.value.login == "yutkat")' > assets/github-followed-ranking.json

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-followed-ranking
          path: |
            github-followed-ranking.json

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'generated'
          git push
        if: steps.diff.outcome == 'failure'
